[Template merge] python accept-lemmas

diff --git a/tools/spellcheckers/test/accept-all-lemmas.sh.in b/tools/spellcheckers/test/accept-all-lemmas.sh.in
--- a/tools/spellcheckers/test/accept-all-lemmas.sh.in
+++ b/tools/spellcheckers/test/accept-all-lemmas.sh.in
@@ -1,37 +1,52 @@
 #!/bin/bash
-# @configure_input@
-
-# Automake interprets the exit status as follows:
-# - an exit status of 0 will denote a success
-# - an exit status of 77 a skipped test
-# - an exit status of 99 a hard error
-# - any other exit status will denote a failure.
-
-# To run this test script only, do:
+# test script for speller accepting all lemmas
 #
-# make check TESTS=accept-all-lemmas.sh
-
-# This test script will test that all lemmas are accepted by the speller
-
-###### Variables: #######
-GIELLA_LANG=@GTLANG2@
-### in ###
+# change settings here:
 source_files=@abs_top_srcdir@/src/fst/morphology/stems/*.lexc
+# advanced settings
+exclusions=""
+GIELLA_LANG=@GTLANG2@
 speller_dir=@abs_builddir@/../
-exclusions="(CmpN/Only|ShCmp|\+Cmp/SplitR| Rreal | R | Rnoun |\+V\+|NOT-TO-LEMMATEST)"
+speller_archive=$speller_dir/$GIELLA_LANG.zhfst
 
-##### Extract lemmas - add additional egrep pattern as parameters: #####
-##### --include "(pattern1|pattern2|...)"                          #####
-##### --exclude "(pattern1|pattern2|...)"                          #####
-@GTCORE@/scripts/accept-all-lemmas.sh "$speller_dir/$GIELLA_LANG.zhfst" \
-    "$exclusions" \
-    "$source_files"
+# avoid changing common scripting stuff here
+. "$GIELLA_CORE/scripts/termcolors.bash"
+PYTHON=@PYTHON@
+genscript=$GIELLA_CORE/scripts/accept-all-lemmas.py
+divvunspell=@DIVVUNSPELL@
+
+# ensure this is proper run from make check or otherwise set up
+if test -z "$srcdir" ; then
+    printf "%sfail%s %s needs to run from make check or set srcdir=.\n" "$red" \
+        "$reset" "$0"
+    exit 1
+fi
+if ! test -f "$genscript" ; then
+    printf "%sskip%s missing generator script %s\n" "$light_blue" "$reset" \
+        "$genscript"
+    exit 77
+fi
+if ! test -f "$divvunspell" ; then
+    printf "%sskip%s missing divvunspell\n" "$light_blue" "$reset"
+    exit 77
+fi
+for f in $source_files ; do
+    if ! test -f "$f" ; then
+        printf "%sfail%s no lexc files matching %s\n" "$red" "$reset" "$f"
+        exit 1
+    fi
+done
+
+$PYTHON -- "$genscript" -z "$speller_archive" \
+    -D "$divvunspell" \
+    $exclusions \
+    $source_files
 
 rv=$?
 if test $rv = 77 ; then
-    echo skipped
+    printf "%sskipped%s\n" "$light_blue" "$reset"
     exit 77
 elif test $rv -ge 1 ; then
-    echo failed
+    printf "%sfailed%s\n" "$red" "$reset"
     exit 1
 fi
