[Template merge - langs/und] Added option to specify language variant, to allow testing spellers for alternative writing systems, alternative orthographies, different countries etc.

diff --git a/devtools/test_voikkospell_suggestions.sh.in b/devtools/test_voikkospell_suggestions.sh.in
--- a/devtools/test_voikkospell_suggestions.sh.in
+++ b/devtools/test_voikkospell_suggestions.sh.in
@@ -29,6 +29,7 @@ speller_input=speller_input.${engine}.txt
 speller_output=speller_output.${engine}.txt
 speller_timeusage=speller_timeusage.${engine}.txt
 speller_results="$SCRIPT_DIR/speller_result_${file_spesifier}.${engine}.html"
+variant=""
 
 # Other variables:
 DATE=$(date +%Y%m%d)
@@ -39,11 +40,18 @@ function print_usage() {
     echo "Test the $giella_lang speller using voikkospell and typos data"
     echo
     echo "  -h, --help          Print this usage info"
+    echo "  -v, --variant       Select locale variant to test, like dialect,"
+    echo "                      country, alternative writing system etc."
+    echo "                      Specify the whole filename, except the suffix"
+    echo "                      .zhfst, e.g.:"
+    echo "                      -v ${giella2c_lang}_NO"
+    echo "                      or e.g.:"
+    echo "                      --variant ${giella2c_lang}_Cyrl"
     echo
 }
 
 # Wrong usage - short instruction:
-if test $# -ge 2 ; then
+if test $# -ge 3 ; then
     print_usage
     exit 1
 fi
@@ -53,9 +61,44 @@ while test $# -ge 1 ; do
     if test x$1 = x--help -o x$1 = x-h ; then
         print_usage
         exit 0
+    elif test x$1 = x--variant -o x$1 = x-v ; then
+        # If -v is not followed by anything - fail:
+        if test -z "$2" ; then
+            echo "ERROR: please specify the variant you want to use"
+            echo
+            print_usage
+            exit 1
+        # If the next argument is a new option (not a variant), then fail:
+        elif [[ "$2" = \-* ]] ; then
+            echo "ERROR: please specify the variant you want to use"
+            echo
+            print_usage
+            exit 1
+        else
+            variant="$2"
+            shift
+        fi
     fi
     shift
 done
+
+# if a variant was specified, use that as the speller file:
+if test "x$variant" != x ; then
+    giella2c_lang=$variant
+fi
+
+# Check that the speller file does exist:
+spellerfile="$top_builddir/$spellerdir/${giella2c_lang}.zhfst"
+if test ! -f $spellerfile ; then
+    echo "ERROR: Speller file not found:" 1>&2
+    echo "$spellerfile" 1>&2
+    echo  1>&2
+    exit 1
+fi
+
+# Include language (variant) as part of the filename, so that one can keep
+# track of and compare different variants:
+speller_results=$speller_results.${giella2c_lang}.html
 
 # Add easter egg version info trigger:
 echo "nuvviDspeller	Divvun" > $SCRIPT_DIR/$speller_test_data
