[Template merge] fix generate lemma test lexc checks

diff --git a/src/fst/morphology/test/generate-noun-lemmas.sh.in b/src/fst/morphology/test/generate-noun-lemmas.sh.in
--- a/src/fst/morphology/test/generate-noun-lemmas.sh.in
+++ b/src/fst/morphology/test/generate-noun-lemmas.sh.in
@@ -38,6 +38,11 @@ if ! test -f "$analyser_file.hfstol" ; then
         "$analyser_file"
     exit 1
 fi
+if ! test -f "$source_file" ; then
+    printf "%sfail%s missing lexc file %s\n" "$red" "$reset" \
+        "$source_file"
+    exit 1
+fi
 
 "$genscript" -l "$source_file" \
     -g "$generator_file.hfstol" -a "$analyser_file.hfstol" \
