[Template merge] lemma test config.json

diff --git a/src/fst/morphology/test/generate-adjective-lemmas.sh.in b/src/fst/morphology/test/generate-adjective-lemmas.sh.in
--- a/src/fst/morphology/test/generate-adjective-lemmas.sh.in
+++ b/src/fst/morphology/test/generate-adjective-lemmas.sh.in
@@ -1,21 +1,11 @@
 #!/bin/bash
 # Test script for adjective lemma generation
 #
-# change settings here:
+# change settings in: config.json.in
+# do not touch this file
 
 POS=adjectives
-source_file=@abs_srcdir@/../stems/${POS}.lexc
-generator_file=@abs_builddir@/../../generator-gt-norm
-analyser_file=@abs_builddir@/../../analyser-gt-norm
-tags="+A+Msc+Sg+Nom+Indef"
-# advanced settings (leave empty or write full args)
-xtags="-t +A+Msc+Sg+Nom+Def -t +A+Comp+Msc+Sg+Nom+Def -t +A+Superl+Msc+Sg+Nom+Def"
-# {in,ex}clusions are given in arrays to retain spaces, for example:
-# inclusions=("--include" "REG EX" "--include" "EGERG XEX")
-inclusions=()
-exclusions=("--exclude" "(adjcmp1|ELDRI|ELSTUR|adj_def)")
-
-# avoid changing common scripting stuff here:
+CONFIG=@abs_builddir@/config.json
 
 . "$GIELLA_CORE/scripts/termcolors.bash"
 genscript=@GTLEMMATEST@
@@ -31,26 +21,14 @@ if ! test -f "$genscript" ; then
         "$genscript"
     exit 77
 fi
-if ! test -f "$generator_file.hfstol" ; then
-    printf "%sfail%s missing generator FSA %s.hfstol\n" "$red" "$reset" \
-        "$generator_file"
-    exit 1
-fi
-if ! test -f "$analyser_file.hfstol" ; then
-    printf "%sfail%s missing analyser FSA %s.hfstol\n" "$red" "$reset" \
-        "$analyser_file"
-    exit 1
-fi
-if ! test -f "$source_file" ; then
-    printf "%sfail%s missing lexc file %s\n" "$red" "$reset" \
-        "$source_file"
+if ! test -f "$CONFIG" ; then
+    printf "%sfail%s missing config file %s\n" "$red" "$reset" \
+        "$CONFIG"
     exit 1
 fi
 
-"$genscript" -l "$source_file" \
-    -g "$generator_file.hfstol" -a "$analyser_file.hfstol" \
-    -t "$tags" $xtags "${inclusions[@]}" "${exclusions[@]}" \
-    -E @LOG_VIEWER@
+"$genscript" -c "$CONFIG" -P "$POS" -E "@LOG_VIEWER@" \
+    -L "@abs_top_builddir@/docs/testlogs/$POS-lemmas.md"
 rv=$?
 if test $rv = 77 ; then
     printf "%sskipped%s\n" "$light_blue" "$reset"
@@ -58,4 +36,6 @@ if test $rv = 77 ; then
 elif test $rv -gt 0 ; then
     printf "%sfailed%s\n" "$red" "$reset"
     exit 1
+else
+    printf "%spassed%s\n" "$green" "$reset"
 fi
diff --git a/src/fst/morphology/test/generate-verb-lemmas.sh.in b/src/fst/morphology/test/generate-verb-lemmas.sh.in
--- a/src/fst/morphology/test/generate-verb-lemmas.sh.in
+++ b/src/fst/morphology/test/generate-verb-lemmas.sh.in
@@ -1,20 +1,10 @@
 #!/bin/bash
 # Test script for verb lemma generation
 #
-# change settings here:
+# change settings in config.json.in
+# do not touch this file
 POS=verbs
-source_file=@abs_srcdir@/../stems/${POS}.lexc
-generator_file=@abs_builddir@/../../generator-gt-norm
-analyser_file=@abs_builddir@/../../analyser-gt-norm
-tags=+V+Inf
-# advanced settings (leave empty or write full args)
-xtags="-t +V+Inf+Pass"
-# {in,ex}clusions are given in arrays to retain spaces, for example:
-# inclusions=("--include" "REG EX" "--include" "EGERG XEX")
-inclusions=()
-exclusions=()
-
-# avoid changing common scripting stuff here:
+CONFIG=@abs_builddir@/config.json
 
 . "$GIELLA_CORE/scripts/termcolors.bash"
 genscript=@GTLEMMATEST@
@@ -30,26 +20,14 @@ if ! test -f "$genscript" ; then
         "$reset" "$genscript"
     exit 77
 fi
-if ! test -f "$generator_file.hfstol" ; then
-    printf "%sfail%s missing generator FSA %s.hfstol\n" "$red" "$reset" \
-        "$generator_file"
-    exit 1
-fi
-if ! test -f "$analyser_file.hfstol" ; then
-    printf "%sfail%s missing analyser FSA %s.hfstol\n" "$red" "$reset" \
-        "$analyser_file"
-    exit 1
-fi
-if ! test -f "$source_file" ; then
-    printf "%sfail%s missing lexc file %s\n" "$red" "$reset" \
-        "$source_file"
+if ! test -f "$CONFIG" ; then
+    printf "%sfail%s missing config file %s\n" "$red" "$reset" \
+        "$CONFIG"
     exit 1
 fi
 
-"$genscript" -l "$source_file" \
-    -g "$generator_file.hfstol" -a "$analyser_file.hfstol" \
-    -t "$tags" $xtags "${inclusions[@]}" "${exclusions[@]}" \
-    -E @LOG_VIEWER@ 
+"$genscript" -c "$CONFIG" -P "$POS" -E "@LOG_VIEWER@" \
+    -L "@abs_top_builddir@/docs/testlogs/$POS-lemmas.md"
 rv=$?
 if test $rv = 77 ; then
     printf "%sskipped%s" "$light_blue" "$reset"
@@ -57,4 +35,6 @@ if test $rv = 77 ; then
 elif test $rv -gt 0 ; then
     printf "%sfailed%s" "$red" "$reset"
     exit 1
+else
+    printf "%spassed%s" "$green" "$reset"
 fi
