[Template merge] new version of multichar test

diff --git a/src/fst/morphology/test/missing-multichars.sh.in b/src/fst/morphology/test/missing-multichars.sh.in
--- a/src/fst/morphology/test/missing-multichars.sh.in
+++ b/src/fst/morphology/test/missing-multichars.sh.in
@@ -1,23 +1,42 @@
 #!/bin/bash
+# Test script for undeclared multichar_symbols
+#
+# change settings here in config.json.in
+# do not touch this file
+CONFIG=@abs_builddir@/config.json
+. "$GIELLA_CORE/scripts/termcolors.bash"
+testrunner="@GTMULTICHARTEST@"
 
 # ensure that we are ran from make or setup properly
 if test -z "$srcdir" ; then
-    echo "srcdir= not set, this must be run from make or set srcdir=."
+    printf "%sfail%s %s needs to run from make check or set srcdir=.\n" \
+        "$red" "$reset" "$0"
     exit 2
 fi
 if test -z "$GIELLA_CORE" ; then
-    echo "GIELLA_CORE= must point to giella-core"
+    printf "%sfail%s GIELLA_CORE= must point to giella-core\n" "$red" "$reset"
     exit 2
 fi
-testrunner="@GTMULTICHARTEST@"
 if ! test -x "$testrunner" ; then
-    echo "missing test runner from giellaltlextools: $testrunner"
+    printf "%sskip% missing test runner from giellaltlextools: $testrunner\n" \
+        "$light_blue" "$reset"
     echo "(hint: pipx upgrade giellaltlextools)"
     exit 77
 fi
-lexc=@builddir@/../.generated/lexicon.catted.lexc
-if ! test -f $lexc ; then
-    echo combined $lexc missing or disappeared
+if ! test -f "$CONFIG" ; then
+    printf "%sfail%s missing config.json at $CONFIG" "$red" "$reset"
     exit 1
 fi
-$testrunner -l $lexc
+$testrunner -c "$CONFIG" -E "@LOG_VIEWER@" \
+    -L "@abs_top_srcdir@/docs/testlogs/multichar_symbols.md"
+rv=$?
+if test $rv = 77 ; then
+    printf "%sskipped%s" "$light_blue" "$reset"
+    exit 77
+elif test $rv -gt 0 ; then
+    printf "%sfailed%s" "$red" "$reset"
+    exit 1
+else
+    printf "%spassed%s" "$green" "$reset"
+fi
+
