[Template merge - langs/und] Skip Xerox testing if no test data is found. Added comments.
git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/fao@110752 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/src/phonology/pair-test-negative.sh.in b/test/src/phonology/pair-test-negative.sh.in
--- a/test/src/phonology/pair-test-negative.sh.in
+++ b/test/src/phonology/pair-test-negative.sh.in
@@ -22,12 +22,20 @@ EXTEDITOR=@SEE@
 if test -x ${TWOLC} ; then
   if test -f ${SOURCEFILE} ; then
     grep '^!\$' ${SOURCEFILE} | cut -d' ' -f2- > ${TESTDATA}
+    # If we found no test data, skip the testing:
+    if ! test -s ${TESTDATA} ; then
+        rm -f ${TESTDATA}
+        exit 77
+    fi
+    # Print the testing script to a script file:
     ${PRINTF} "\
 install-binary ${FSTFILE}\n\
 pair-test-file ${TESTDATA} ${TESTRESULT}\n\
 quit\n" \
     	> ${TWOLCSCRIPT}
+    # Run the script file:
     ${TWOLC} -q < ${TWOLCSCRIPT}
+    # If there are errors and fails, open the output file in SEE and exit w fail
     if grep 'ACCEPTED' ${TESTRESULT} > /dev/null ; then
         if test x$EXTEDITOR != "x"; then
             $EXTEDITOR ${TESTRESULT}
@@ -36,10 +44,10 @@ quit\n" \
     fi
     rm -f ${TWOLCSCRIPT} ${TESTDATA} ${TESTRESULT}
   else
-      echo ${SOURCEFILE} not found
+      echo "*** ${SOURCEFILE} not found ***"
       exit 77
   fi
 else
-    echo ${TWOLC} not found
+    echo "*** ${TWOLC} not found ***"
     exit 77
 fi
diff --git a/test/src/phonology/pair-test-positive.sh.in b/test/src/phonology/pair-test-positive.sh.in
--- a/test/src/phonology/pair-test-positive.sh.in
+++ b/test/src/phonology/pair-test-positive.sh.in
@@ -3,9 +3,9 @@
 ## Copyright: Sámediggi/Divvun/UiT
 ## Licence: GPL v3+
 
-# Shell script to extract positive test pairs from the twolc source file and
+# Shell script to extract negative test pairs from the twolc source file and
 # run them against the compiled twolc file using the pair-test command. All
-# pair strings should be accepted. For the Xerox twolc tool.
+# pair strings should be rejected. For the Xerox twolc tool.
 # If the test fails, the output will be
 # opened in SubEthaEdit (MacOSX only) if installed.
 
@@ -15,31 +15,39 @@ GTLANG=@GTLANG@
 SOURCEFILE=${srcdir}/../../../src/phonology/${GTLANG}-phon.twolc
 FSTFILE=../../../src/phonology/${GTLANG}-phon.compose.xfst
 TWOLCSCRIPT=twolcscript.sh
-TESTDATA=positive-pairs.txt
-TESTRESULT=positive-pairs-out.txt
+TESTDATA=negative-pairs.txt
+TESTRESULT=negative-pairs-out.txt
 EXTEDITOR=@SEE@
 
 if test -x ${TWOLC} ; then
   if test -f ${SOURCEFILE} ; then
-    grep '^!€' ${SOURCEFILE} | cut -d' ' -f2- > ${TESTDATA}
+    grep '^!\$' ${SOURCEFILE} | cut -d' ' -f2- > ${TESTDATA}
+    # If we found no test data, skip the testing:
+    if ! test -s ${TESTDATA} ; then
+        rm -f ${TESTDATA}
+        exit 77
+    fi
+    # Print the testing script to a script file:
     ${PRINTF} "\
 install-binary ${FSTFILE}\n\
 pair-test-file ${TESTDATA} ${TESTRESULT}\n\
 quit\n" \
     	> ${TWOLCSCRIPT}
+    # Run the script file:
     ${TWOLC} -q < ${TWOLCSCRIPT}
-    if grep -E '(REJECTED|Error)' ${TESTRESULT} > /dev/null ; then
+    # If there are errors and fails, open the output file in SEE and exit w fail
+    if grep 'ACCEPTED' ${TESTRESULT} > /dev/null ; then
         if test x$EXTEDITOR != "x"; then
             $EXTEDITOR ${TESTRESULT}
         fi
         exit 1
     fi
-#    rm -f ${TWOLCSCRIPT} ${TESTDATA} ${TESTRESULT}
+    rm -f ${TWOLCSCRIPT} ${TESTDATA} ${TESTRESULT}
   else
-      echo ${SOURCEFILE} not found
+      echo "*** ${SOURCEFILE} not found ***"
       exit 77
   fi
 else
-    echo ${TWOLC} not found
+    echo "*** ${TWOLC} not found ***"
     exit 77
 fi
